// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0LFu5Yz83_8LHP6v4Qe4uk_hzeCggDLU',
    appId: '1:565553170712:web:f3677cca6f562e4b48766d',
    messagingSenderId: '565553170712',
    projectId: 'food-recipe-app-123',
    authDomain: 'food-recipe-app-123.firebaseapp.com',
    storageBucket: 'food-recipe-app-123.firebasestorage.app',
    measurementId: 'G-K5QQ2VLT5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBastpkQ36ecoFNklG9Q2uZ3X4PqGnothY',
    appId: '1:565553170712:android:856a318759f584b448766d',
    messagingSenderId: '565553170712',
    projectId: 'food-recipe-app-123',
    storageBucket: 'food-recipe-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdpj6tDWYvMc3h9s6YkzVqeTqehYwK7GQ',
    appId: '1:565553170712:ios:1bf6622fd4d9637a48766d',
    messagingSenderId: '565553170712',
    projectId: 'food-recipe-app-123',
    storageBucket: 'food-recipe-app-123.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdpj6tDWYvMc3h9s6YkzVqeTqehYwK7GQ',
    appId: '1:565553170712:ios:1bf6622fd4d9637a48766d',
    messagingSenderId: '565553170712',
    projectId: 'food-recipe-app-123',
    storageBucket: 'food-recipe-app-123.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0LFu5Yz83_8LHP6v4Qe4uk_hzeCggDLU',
    appId: '1:565553170712:web:2bacb7086da3fc9548766d',
    messagingSenderId: '565553170712',
    projectId: 'food-recipe-app-123',
    authDomain: 'food-recipe-app-123.firebaseapp.com',
    storageBucket: 'food-recipe-app-123.firebasestorage.app',
    measurementId: 'G-R7906PEPSW',
  );
}
